try:
    pass
except Exception as e: 
    print(e)
# general exceptions use
else:
    pass
finally:
    pass